name: Build, test and verify `akka-dev-cert`

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name:
        id: cache-mvn
        uses: actions/cache@v4
        env:
          cache-name: cache-mvn-dependencies
        with:
          # mvn caches dependencies in `~/.m2/repository` on Linux/macOS
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          path: |
            ~/.m2/repository
      - name: Configure Maven settings for Akka Secure
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <profiles>
              <profile>
                <id>akka</id>
                <properties>
                  <akka.token>${MAVEN_PASSWORD}</akka.token>
                </properties>
              </profile>
            </profiles>
            <activeProfiles>
                <activeProfile>akka</activeProfile>
            </activeProfiles>
          </settings>
          EOF

      - name: Make mvnw executable
        run: chmod +x mvnw
      - name: Build, Test, and Verify
        run: ./mvnw test
